<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?= $config->site_title() ?></title>
        <meta name="keywords" content="PHP,Circuit Breaker,Circuit Breaker Pattern,Micro Services,Fault Tolerance" />
        <meta name="description" content="Ganesha is PHP implementation of Circuit Breaker pattern which has multi strategies to avoid cascading failures and supports various storages to record statistics." />
        <link href="http://fonts.googleapis.com/css?family=News+Cycle:400,700" rel="stylesheet" />
        <link href="default.css" rel="stylesheet" type="text/css" media="all" />
    </head>
    <body>
        <div id="header" class="container">
        	<div id="logo">
        		<h1><a href="/ganesha/">Ganesha</a></h1>
        	</div>
        	<div id="menu">
        		<ul>
        			<li><a href="/ganesha/" title="">Top</a></li>
        			<li><a href="./usage.html" title="">Usage</a></li>
        		</ul>
        	</div>
        </div>
        <div id="<?= $bg ?>">
        	<div class="container">
        		<?php if (isset($title)): ?>
        			<div class="title">
        				<h2><?= $title ?></h2>
        				<?php if (isset($subtitle)): ?>
        					<span class="byline"><?= $subtitle ?></span>
        				<?php endif; ?>
        			</div>
        		<?php endif; ?>

        		<?= $content ?>

        	</div>
        </div>
        <div id="copyright" class="container">
        	<p>Generated by <a href="https://github.com/kentaro/soushi">Soushi</a>.</p>
    	<p>Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>.</p>
        </div>
    </body>
</html>
